// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToIIS
{
    internal sealed partial class Vsix
    {
        public const string Id = "AttachToIIS.d983ce74-e5ee-4b1b-b751-10dbd675c846";
        public const string Name = "Attach to IIS";
        public const string Description = @"The easiest way to attach to IIS, IIS Express. This version is compatible with Visual Studio 2022.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Igor Perkovsky";
        public const string Tags = "Attach, Attach to Process, Attach to Process IIS";
    }
}
