// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace AttachToIIS
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string AttachToIISString = "e9148e33-714a-40bf-ab64-a024b0d27119";
        public static Guid AttachToIIS = new Guid(AttachToIISString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x0001;
        public const int AttachToIISCommand = 0x0100;
        public const int AttachToIISExpressCommand = 0x0200;
    }
}